---
- name: Converge
  hosts: all
  #become: true

  vars:
    pip_install_packages:
      # Test installing a specific version of a package.
      - name: ipaddress
        version: "1.0.18"
      # Test installing a package by name.
      - colorama

  pre_tasks:
    - name: Update apt cache.
<<<<<<< HEAD
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
=======
      apt: update_cache=true cache_valid_time=600
>>>>>>> 506fa00 (Attempt to fix ansible_facts deprecation warnings.)
      when: ansible_facts.os_family == 'Debian'

    - name: Set package name for older OSes.
      ansible.builtin.set_fact:
        pip_package: python-pip
      when: >
        (ansible_facts.os_family == 'RedHat') and (ansible_facts.distribution_major_version | int < 8)
        or (ansible_facts.distribution == 'Debian') and (ansible_facts.distribution_major_version | int < 10)
        or (ansible_facts.distribution == 'Ubuntu') and (ansible_facts.distribution_major_version | int < 18)

  roles:
    - role: geerlingguy.pip
